Allow for larger mails with attachments
zaxbux/oc-gmaildriver-plugin pull request #3
Opened 2020-02-11 21:57 UTC by alxy

Currently, you can only send mails with a maximum size of 5MB (MIME-encoded, inlcuding attachments)
With this change, a chunked and resumable upload with multiple requests is used.
The maximum mail size is now the Gmail limit of 25MB.

2020-02-28 04:05 UTC, zaxbux commented
I'll take a look! Thanks.

2020-02-28 06:40 UTC, zaxbux commented on classes/GmailTransport.php
> +            if(strlen($message->toString()) < 5 * 1024 * 1024) {
This `if` statement can be removed, as the non-chunked sending method becomes redundant, leaving the chunked sending method which can handle any size (up to the max 35MB).

2020-02-28 06:41 UTC, zaxbux commented on classes/GmailTransport.php
> +                $gmailMessage = $this->googleAPI->getServiceGmail()->users_messages->send('me', $gmailMessage, ['uploadType' => 'resumable']); // Resumable upload type
Change the `uploadType` to use the class constant `Google_Http_MediaFileUpload::UPLOAD_RESUMABLE_TYPE` instead of a string.

2020-02-28 06:44 UTC, zaxbux requested changes
Confirmed that sending messages larger than 5MB is not possible with the regular API. Just two small changes I need from you, before I merge. I'll remove the extraneous `base64url` method now that it's not required to encode the message. Thanks for contributing!

2020-03-06 09:29 UTC, alxy commented
Hi, thanks for the review. I decided to go with this hybrid approach as the resumable upload will always need two HTTP requests, no matter how small the message is and even if there are no attachments, if I get that correctly:
> With this method, you use a session initiating request, which optionally can include metadata. This is a good strategy to use for most applications, since it also works for smaller files at the cost of one additional HTTP request per upload.
This I would say it is a good idea to go with this conditioned approach. What do you think?

2020-03-06 17:12 UTC, zaxbux commented
For the sake of simplicity and since the resumable session handles any size up to the maximum, I think it's better to use that one. Additionally, the overhead of one additional HTTP request (especially since the initial one is just metadata) is minimal. There is also the benefit of not having to rely on an encoding function to use the simple upload type, since the resumable type uses the native `toString()` method of the `Swift_Mime_SimpleMimeEntity` class.

I believe this plugin qualifies as "most applications":

> This is a good strategy to use for most applications
>
> &mdash; https://developers.google.com/gmail/api/guides/uploads

2020-03-10 02:20 UTC, zaxbux approved these changes

2020-03-10 04:53 UTC, merged

2020-03-10 04:55 UTC, zaxbux reviewed
Will make requested changes.

2020-03-10 13:47 UTC, alxy commented
Thanks, havent found the time yet!